# Generated by Django 4.0.6 on 2022-07-25 17:16
from django.utils.crypto import get_random_string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='auth',
            field=models.CharField(default=get_random_string(length=32), max_length=32),
            preserve_default=False,
        ),
    ]
