# Generated by Django 4.0.6 on 2022-07-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_eventuser_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='email',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.eventuser')),
            ],
        ),
    ]
