# Generated by Django 4.0.6 on 2022-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_eventuser_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=32)),
                ('stage', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('email', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=12)),
                ('filter1', models.CharField(max_length=32)),
                ('filter2', models.CharField(max_length=32)),
                ('filter3', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Phase1',
            fields=[
                ('email', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('q1', models.CharField(max_length=5)),
                ('q2', models.CharField(max_length=5)),
                ('q3', models.CharField(max_length=5)),
                ('q4', models.CharField(max_length=5)),
                ('q5', models.CharField(max_length=5)),
                ('q6', models.CharField(max_length=5)),
                ('q7', models.CharField(max_length=5)),
                ('q8', models.CharField(max_length=5)),
                ('q9', models.CharField(max_length=5)),
                ('q10', models.CharField(max_length=5)),
                ('q11', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=12)),
                ('totalscore', models.FloatField()),
                ('logicalscore', models.FloatField()),
                ('excelscore', models.FloatField()),
                ('mathscore', models.FloatField()),
                ('analyticalscore', models.FloatField()),
            ],
        ),
    ]
