# Generated by Django 4.0.6 on 2022-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_actionstage_group_phase1_phase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase2',
            name='group',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
